name: Debug build

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
  workflow_dispatch: ~

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Build
        run: |
          pip install -r requirements.txt
          pyinstaller --uac-admin -F --i imgs/icon.ico gui.py
          xcopy imgs dist\imgs /I /E
          xcopy README.md dist
          ren dist AutoSimulatedUniverse
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: AutoSimulatedUniverse
          path: AutoSimulatedUniverse
